CREATE TABLE tbCliente /*padrão de construção de tabelas*/
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(100),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1));

/*COMANDO PARA EXCLUIR UMA TABELA
Use Sucos;

DROP TABLE TABELA_DE_VENDEDORES; - ele excluí a tabela toda, tem que ter cuidado
*/




