CREATE TABLE tbProduto (
PRODUTO VARCHAR(20) NULL, /*NULL = esse campo aceita valores nulos ou vazioss*/
NOME VARCHAR(20) NULL,
EMBALAGEM VARCHAR(20) NULL,
TAMANHO VARCHAR(50) NULL,
SABER VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL);

